### ISSUE TITLE
Añadir gallego

### ISSUE THREAD

**Issue by m1guelpiedrafita** [vrruiz/visualino#21]
See below

**Comment by vrruiz** [comment]
Hola Miguel. Sí, este proyecto soporta traducciones y, por desgracia, ya
está traducido al español. De todas formas, si quieres revisarlas, los
ficheros de traducción andan en el directorio /ts/ (hace falta el programa
Qt Translator para editarlos).

**Comment by tecnoloxia** [comment]
Como tengo que hacer para aportar una traducción a galego?
Gracias

**Comment by vrruiz** [comment]
Puedes modificar los ficheros en portugués (o en español). Hay dos
cosas a traducir: los bloques y el programa.

- Para traducir los bloques puedes mirar en este directorio
https://github.com/vrruiz/roboblocks/tree/master/lang Sólo tienes que
copiar uno de esos ficheros como gl-es.js.
- Luego, para traducir el resto del interfaz puedes usar Qt
Linguistic. Los ficheros de traducciones del interfaz andan por aquí:
https://github.com/vrruiz/visualino/tree/master/ts

Si tienes más dudas, puedes resolverlas por aquí o en los foros.

**Comment by tecnoloxia** [comment]
Ok, ya tengo los ficheros. No me permite subilos aquí. Están en [google drive](https://drive.google.com/file/d/0B6CqFl4gn5RCS2xPUURGemxrb3c/view?usp=sharing).

**Comment by m1guelpiedrafita** [comment]
@tecnoloxia Te los subía Github.
Enlaces: https://github.com/vrruiz/roboblocks/pull/4
https://github.com/vrruiz/visualino/pull/22

**Comment by vrruiz** [comment]
Gracias por la traducción y por enviarlo a github. ¡Están ya en los repos!
En cuanto pueda genero una nueva versión con Visualino en gallego.

**Comment by m1guelpiedrafita** [comment]
Closing issue. You can reopen it if you need

**Comment by tecnoloxia** [comment]
Muchas gracias. Estoy preparando unas prácticas con visualino y me gustaría contar con el software en galego para la documentación.
