### ISSUE TITLE
Arduino Nano

### ISSUE THREAD

**Issue by fpalacios1203** [vrruiz/visualino#46]
Hola. Quisiera saber como se puede modificar, o agregar una opción extra, para poder programar el arduino nano 328p. Actualmente no funciona con el ide actualizado, por el cambio de bootloader en las partidas nuevas. Para poder cargar un skecth en el IDE de arduino hace falta especificar la opcion "Old Bootloader", pero en Visualino no se puede especificar esto. Utilizando un Ide Arduino no actualizado funciona, pero seria mas cómodo si se puede modificar esto. Gracias

**Comment by vrruiz** [comment]
Hola Fabián. Como te he comentado en Twitter, el problema está en que las versiones nuevas del IDE de Arduino usa el identificador del Nano para las placas nuevas y han creado un nuevo identificador para los Nanos que necesitan el 'bootloader' viejo. Está añadido ahora como placa nueva en el menú desplegable.
