### ISSUE TITLE
Add support for zum board (Arduino BT)

### ISSUE THREAD

**Issue by Obijuan** [vrruiz/visualino#9]
Currently only arduino uno, mega and nano are supported.  The zum board is compatible with Arudino BT. It allows to download programs through bluetooth. It is great for teaching robot programing to kids.

It would be great if the zum board is added to visualino

Great tool! Thanks! :-)

**Comment by Obijuan** [comment]
More information.

The only difference between arduino uno and zum board is that the baudrate should be changed to 19200 by means of the param:   -b19200  when calling avrdude

This is what is executed when uploading to the zum:

avrdude -C/home/obijuan/arduino-1.6.3/hardware/tools/avr/etc/avrdude.conf -q -q -patmega328p -carduino -P/dev/ttyUSB0 -b19200 -D -Uflash:w:/tmp/build2154442348667408074.tmp/Blink.cpp.hex:i

This is what is executed when uploading to arduino uno:

avrdude -C/home/obijuan/arduino-1.6.3/hardware/tools/avr/etc/avrdude.conf -q -q -patmega328p -carduino -P/dev/ttyUSB0 -b115200 -D -Uflash:w:/tmp/build2154442348667408074.tmp/Blink.cpp.hex:i

**Comment by Obijuan** [comment]
I've read the code and now I undestand it a little better :-)  For uploading code to arduino boards Visualino is calling arduino ide.  I've successfully upload code to zum board with this command in the console:

arduino --upload --board arduino:avr:bt --port /dev/ttyUSB0 /tmp/visualino/visualino.ino

So, for implementing the zum board only is needed to identify it as:  "arduino:avr:bt"  :-)

**Comment by Obijuan** [comment]
Success!!!  :-)   I have emitted a pull request with the fix

**Comment by vrruiz** [comment]
Thanks a lot! This is the first contribution to the IDE itself, wee! :))

I've merged the pull request, but I think support is still needed to set the baud rate on the command line. Can you confirm?

**Comment by vrruiz** [comment]
I see that boards.txt defines bt.upload.speed=19200 by default, so no need.

**Comment by Obijuan** [comment]
I will close this issue. Thanks a lot!  :-)
